### ISSUE TITLE
如何抓包imaotai

### ISSUE THREAD

**Issue by kennylbj** [yazhuo-wyze/imaotai#1]
imaotai似乎做了certificate pinning, 没法直接抓，作者能提示一下如何解决抓包的问题吗？是用到逆向来更改内置证书？

**Comment by yazhuo-wyze** [comment]
我不懂app端开发，按照网上别人提供的文档去实现的。

**Comment by kennylbj** [comment]
抓不了包担心的是如果app的api换了，就没法工作了

**Comment by yazhuo-wyze** [comment]
skidoodiudiu  可以微信问问这位大佬。
