### ISSUE TITLE
增加领取能量接口

### ISSUE THREAD

**Issue by GoToBoy** [yazhuo-wyze/imaotai#11]
对py不熟悉，这里有接口可以参考，大佬有空可以添加一下

https://github.com/wd210010/just_for_happy/blob/main/imaotai.py

**Comment by yazhuo-wyze** [comment]
Ok.

--------------------------------------------------------
Beijing Cloud  Service｜ 北京云服务
Yazhuo Dong ｜ 董亚卓
+86-18611643318
