### ISSUE TITLE
token 失效，没有实现邮件通知

### ISSUE THREAD

**Issue by cjumna** [yazhuo-wyze/imaotai#13]
今天发现有几个账号token失效，但是没看到邮件通知，我哪里设置出错了？

ITEM_MAP = {
    "10213": "53%vol 500ml贵州茅台酒（癸卯兔年）",
    "10214": "53%vol 375ml×2贵州茅台酒（癸卯兔年）",
    "10056": "53%vol 500ml茅台1935",
    "2478": "53%vol 500ml贵州茅台酒（珍品）"
}

# 需要预约的商品(默认只预约2个兔茅)
########################
ITEM_CODES = ['10213', '10214']

# 预约失败的邮件通知，默认不发送，发送需要配置发件人信息（一般为登录过期，token失效）
########################
# 发件人邮箱 ： hello@hi.com
EMAIL_SENDER_USERNAME = "cxxx@163.com"
# 发件人密码：123456
EMAIL_SENDER_PASSWORD = "Xixxxxx"
# 发件人邮箱服务器
SMTP_SERVER = "smtp." + EMAIL_SENDER_USERNAME.split("@")[1]
# 发件人邮箱服务器端口
SMTP_PORT = 25
# 收件人邮箱
EMAIL_RECEIVER = EMAIL_SENDER_USERNAME
########################

**Comment by yazhuo-wyze** [comment]
邮箱配置都要配置成自己的。

--------------原始邮件--------------
发件人："cjumna ***@***.***&gt;;
发送时间：2023年6月23日(星期五) 中午11:25
收件人："yazhuo-wyze/imaotai" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[yazhuo-wyze/imaotai] token 失效，没有实现邮件通知 (Issue #13)
-----------------------------------

 

 
今天发现有几个账号token失效，但是没看到邮件通知，我哪里设置出错了？
 
ITEM_MAP = {
 "10213": "53%vol 500ml贵州茅台酒（癸卯兔年）",
 "10214": "53%vol 375ml×2贵州茅台酒（癸卯兔年）",
 "10056": "53%vol 500ml茅台1935",
 "2478": "53%vol 500ml贵州茅台酒（珍品）"
 }
 
需要预约的商品(默认只预约2个兔茅)
 
########################
 ITEM_CODES = ['10213', '10214']
 
预约失败的邮件通知，默认不发送，发送需要配置发件人信息（一般为登录过期，token失效）
 
########################
 
发件人邮箱 ： ***@***.***
 
EMAIL_SENDER_USERNAME = ***@***.***"
 
发件人密码：123456
 
EMAIL_SENDER_PASSWORD = "Xixxxxx"
 
发件人邮箱服务器
 
SMTP_SERVER = "smtp." + EMAIL_SENDER_USERNAME.split("@")[1]
 
发件人邮箱服务器端口
 
SMTP_PORT = 25
 
收件人邮箱
 
EMAIL_RECEIVER = EMAIL_SENDER_USERNAME
 ########################

**Comment by cjumna** [comment]
是不是只要输入 邮箱 和密码配置就可以了？
EMAIL_SENDER_USERNAME = "[cxxx@163.com](mailto:cxxx@163.com)"
EMAIL_SENDER_PASSWORD = "Xixxxxx"
其他的都不需要修改了。。。

发件人邮箱服务器

**Comment by yazhuo-wyze** [comment]
> 

涉及一些邮箱方面的，我一会实现一个push+操作。你先不用配置邮箱了。

**Comment by yazhuo-wyze** [comment]
修改为push + 推送，支持定义 配置文件路径。
@cjumna
