### ISSUE TITLE
那个彩釉珍品的item code是多少啊？谢谢

### ISSUE THREAD

**Issue by JohnyWu** [yazhuo-wyze/imaotai#2]
如题

**Comment by JohnyWu** [comment]
2478

**Comment by JohnyWu** [comment]
没事了，已经知道

**Comment by JohnyWu** [comment]
我加了2478这个item后，今天试了下，提示大概是说所申购的商品不在此城市的意思，你试过么？

**Comment by yazhuo-wyze** [comment]
你早上9-10点测试的吗？

**Comment by JohnyWu** [comment]
> 你早上9-10点测试的吗？

对的

**Comment by yazhuo-wyze** [comment]
你明天早上看看手机上可以申购不。

**Comment by JohnyWu** [comment]
> 你明天早上看看手机上可以申购不。

早上不行的时候，我就直接进手机试了，手机可以

**Comment by yazhuo-wyze** [comment]
> > 你明天早上看看手机上可以申购不。
> 
> 早上不行的时候，我就直接进手机试了，手机可以
![4f1083ffe6f0bcf4d00da074f7343c9](https://github.com/yazhuo-wyze/imaotai/assets/106308779/2855aabd-00a5-4b32-bdc8-49a190c763e5)

我早上看程序能申购这个，可能你的城市真不y允许。

**Comment by JohnyWu** [comment]
"当前选择的门店不参与本场申购，请选择另外的门店申购"，这是返回错误。在兔茅2个商品上没发生这个错误，我进app，看到是可以的，点了申购了。

**Comment by yazhuo-wyze** [comment]
> "当前选择的门店不参与本场申购，请选择另外的门店申购"，这是返回错误。在兔茅2个商品上没发生这个错误，我进app，看到是可以的，点了申购了。

我也没研究出来，你会写的话，可以debug试试。提个pr。

**Comment by kennylbj** [comment]
```ts
const getMeta = async () => {
  const timestamp = moment().startOf("day").valueOf();
  const url = `https://static.moutai519.com.cn/mt-backend/xhr/front/mall/index/session/get/${timestamp}`;
  try {
    const result = await axios.get(url);
    if (result.data && result.data.code === 2000) {
      const { sessionId, itemList } = result.data.data;
      const meta = {
        sessionId,
        items: itemList.map((item) => ({
          id: item.itemCode,
          title: item.title,
        })),
      };
      console.log("meta", meta);
      return meta;
    }
    return null;
  } catch (e) {
    console.log("get meta error", e.toString(), e.response.data);
    return null;
  }
};


const meta = await getMeta();
for (const item of meta.items) {
    const { shopId, inventory } = await getShopId(
      user,
      meta.sessionId,
      item.id
    );
    if (shopId && inventory > 0) {
      await reseveProduct(user, meta.sessionId, item.id, shopId);
    }
  }
```

通过这个方式来获取每日的所有产品

**Comment by JohnyWu** [comment]
今天我在一个商品上也遇到彩釉一样的错误"当前选择的门店不参与本场申购，请选择另外的门店申购"

**Comment by yazhuo-wyze** [comment]
> 今天我在一个商品上也遇到彩釉一样的错误"当前选择的门店不参与本场申购，请选择另外的门店申购"

更新一下代码。

**Comment by JohnyWu** [comment]
> > 今天我在一个商品上也遇到彩釉一样的错误"当前选择的门店不参与本场申购，请选择另外的门店申购"
> 
> 更新一下代码，你把你要预约的门店关键字和省份发我看一下。看是不是解决了。

省份 10，关键字 厦门

**Comment by yazhuo-wyze** [comment]
> 

你要预约哪个 item code。

**Comment by kennylbj** [comment]
估计是这个item code在对应城市的inventory是0，没法预约。

**Comment by yazhuo-wyze** [comment]
> 估计是这个item code在对应城市的inventory是0，没法预约。

我修复了这个问题，你更新下代码。你在手机上可以预约这个item code吗？

**Comment by kennylbj** [comment]
我现在用的是我重写的那份代码，跑起来是正常的。
感觉最大的优化点是关键字搜索不好用，很多城市没有对应城市关键字的商家，最好的办法还是用经纬度来匹配最短距离。你能找得到关于商店经纬度的api吗？

**Comment by yazhuo-wyze** [comment]
> 我现在用的是我重写的那份代码，跑起来是正常的。 感觉最大的优化点是关键字搜索不好用，很多城市没有对应城市关键字的商家，最好的办法还是用经纬度来匹配最短距离。你能找得到关于商店经纬度的api吗？

---
我知道这个问题，我也想以地址去查找。但是我不知道API，是最大的问题。另外初始化配置也麻烦。

**Comment by kennylbj** [comment]
又回到了最原始的问题，还是要去壳抓包 :D 😄

配置到还好，用户配置城市名，通过第三方api查到城市对应的经纬度，然后再做匹配。

**Comment by JohnyWu** [comment]
用了新代码，今天都挺正常的

**Comment by JohnyWu** [comment]
今天5.21跑了程序我看只申购了一个商品而已 @yazhuo-wyze

**Comment by JohnyWu** [comment]
今天5.22又试了，还是只申购到了一个，另外2个商品的max_shop_id返回都是0，但是我手机进去看了，厦门确实有货，手机里直接申购厦门门店是成功的 @yazhuo-wyze

**Comment by kennylbj** [comment]
看看有货的门店的名字里有没有“厦门”关键字？

**Comment by yazhuo-wyze** [comment]
关键字读的是门店公司名称。。。

**Comment by JohnyWu** [comment]
> 看看有货的门店的名字里有没有“厦门”关键字？

确定是有的，厦门所有门店都以厦门开头，基本上大部分城市都是这样吧？

**Comment by JohnyWu** [comment]
> 关键字读的是门店公司名称。。。

可以读门店吗？

**Comment by yazhuo-wyze** [comment]
更新下代码，需要重新登录补全信息。会根据地理位置坐标自动预约本市的产品。

请输入你的位置，例如[小区名称]，为你自动预约附近的门店:军安家园
0 : [地区:内蒙古自治区,位置:内蒙古自治区赤峰市红山区军安家园]
请选择位置序号,重新输入请输入[-]:0
已选择 地区:北京市,[北京市海淀区上地十街]附近的门店
输入手机号[13812341234]:1861164****
输入 [1861164****] 验证码[1234]:1234
是否继续添加账号[Y/N]:n

**Comment by JohnyWu** [comment]
最优的逻辑是不是选本城市里数量最多的门店呢？或者说选keyword下数量最多的门店，keyword校验门店名字，而不是公司名字。这样会不会最好？不按照小区附近来。

**Comment by yazhuo-wyze** [comment]
> 

> 最优的逻辑是不是选本城市里数量最多的门店呢？或者说选keyword下数量最多的门店，keyword校验门店名字，而不是公司名字。这样会不会最好？不按照小区附近来。

是本市，根据小区、村落、街道、区域等名称。识别城市省份。然后预约的时候，自动找一个本市出货量最高的那个。

**Comment by JohnyWu** [comment]
05/23/2023 09:46:01 AM  process.py : WARNING  get_location_count : params : 1684771200000, response code : 404, response body : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key></Key><BucketName></BucketName><Resource>/mt-backend/xhr/front/mall/shop/list/slim/v3/631/厦门市/10213/1684771200000</Resource><RequestId>ZNSSP9BNSUKIJQO9</RequestId><HostId>21LCYOXSVN5Z91EV</HostId></Error>

**Comment by JohnyWu** [comment]
早上5.23试了，还是只成功收购到了1个商品，另外2个依然没有申购

**Comment by yazhuo-wyze** [comment]
> 我的keyword用厦门，所以限定了门店了，我在想这个keyword是不是用个什么字符换掉?

昨天我都改了，不使用 keyword了。按市查找了。你看看 代码。

**Comment by JohnyWu** [comment]
> > 我的keyword用厦门，所以限定了门店了，我在想这个keyword是不是用个什么字符换掉?
> 
> 昨天我都改了，不使用 keyword了。按市查找了。你看看 代码。

哦哦对，credential里keyword还在，手工删除掉？

**Comment by yazhuo-wyze** [comment]
> > > 我的keyword用厦门，所以限定了门店了，我在想这个keyword是不是用个什么字符换掉?
> > 
> > 
> > 昨天我都改了，不使用 keyword了。按市查找了。你看看 代码。
> 
> 哦哦对，credential里keyword还在，手工删除掉？

删不删都可以。代码已经不读取了。

**Comment by JohnyWu** [comment]
所以如果公司名字里比如说不存在city"厦门市"这个关键字的，就出不来，对吧？

**Comment by yazhuo-wyze** [comment]
> 所以如果公司名字里比如说不存在city"厦门市"这个关键字的，就出不来，对吧？

已经不关心这个了。你可以看看log，看看报的什么错。

**Comment by JohnyWu** [comment]
早上申购没一个成的，错误是：05/24/2023 09:07:15 AM  process.py : WARNING  get_location_count : params : 1684857600000, response code : 404, response body : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key></Key><BucketName></BucketName><Resource>/mt-backend/xhr/front/mall/shop/list/slim/v3/632/厦门市/10213/1684857600000</Resource><RequestId>UXT6HFR99P48H0OQ</RequestId><HostId>21LCYOXSVN5Z91EV</HostId></Error>
05/24/2023 09:07:15 AM  main.py : ERROR  Expecting value: line 1 column 1 (char 0)

**Comment by JohnyWu** [comment]
貌似直辖市用city可以，非直辖市得用province

**Comment by yazhuo-wyze** [comment]
> 

是的。你可以看看这个接口。之前弄错了，这个接口会把所有某一个地级市所有门店找出来。范围能确定到市。
<img width="757" alt="image" src="https://github.com/yazhuo-wyze/imaotai/assets/106308779/69ca053d-22e3-404c-bd7b-4cff1c1b78af">

**Comment by JohnyWu** [comment]
看到了，我刚手工尝试执行测试完那个api，回头看到你的回复了

**Comment by yazhuo-wyze** [comment]
<img width="662" alt="image" src="https://github.com/yazhuo-wyze/imaotai/assets/106308779/52d9b949-42a9-4326-a0a0-63dd24ea2c04">
@JohnyWu 支持按距离预约了。

**Comment by JohnyWu** [comment]
login.py，建议改下这段，可以更通用些，当然win跑的时候:

# 定义文件路径
home_path = os.getenv("HOME")
path = home_path + '/.imaotai/credentials'
try:
    os.mkdir(home_path + '/.imaotai/')

-->

# 定义文件路径
home_path = os.path.expanduser("~")
path = os.path.join(home_path, '.imaotai', 'credentials')
try:    
    os.mkdir(os.path.join(home_path, '.imaotai'))

**Comment by yazhuo-wyze** [comment]
> login.py，建议改下这段，可以更通用些，在win跑的时候:
> 
> # 定义文件路径
> home_path = os.getenv("HOME") path = home_path + '/.imaotai/credentials' try: os.mkdir(home_path + '/.imaotai/')
> 
> -->
> 
> # 定义文件路径
> home_path = os.path.expanduser("~") path = os.path.join(home_path, '.imaotai', 'credentials') try: os.mkdir(os.path.join(home_path, '.imaotai'))

fixed。

**Comment by limengfanqq** [comment]
可以加一个自动领取耐力值得吗

**Comment by JohnyWu** [comment]
可以加领小茅运么？

**Comment by yazhuo-wyze** [comment]
回头准备研究一下。



--------------------------------------------------------

**Comment by GoToBoy** [comment]
感谢老兄，省了手动力气，请问下：AES_KEY 、AES_IV、SALT 是不是砸壳获取到的？
