### ISSUE TITLE
pushplus收不到消息

### ISSUE THREAD

**Issue by MOLIzhang** [yazhuo-wyze/imaotai#20]
是否只有在预约失败或者token失效时才推送通知

**Comment by yazhuo-wyze** [comment]
只在token失效时推送。

**Comment by JohnyWu** [comment]
> 只在token失效时推送。

我有一个账号，是没有实名认证的情况下申购，返回提示关于“实名认证”的错误，这种是不是也算预约失败？应该会发消息的吗？

**Comment by yazhuo-wyze** [comment]
明天再试试。
