### ISSUE TITLE
中奖结果 能否做个通知。。通知中奖就好

### ISSUE THREAD

**Issue by hcliu987** [yazhuo-wyze/imaotai#23]

**Comment by Liujishou** [comment]
这个官方就通知啊 短信 app都通知！

**Comment by hcliu987** [comment]
还有其他手机号，不登录 app

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Liujishou ***@***.***>
发送时间: Tuesday, July 11, 2023 12:45:04 AM
收件人: yazhuo-wyze/imaotai ***@***.***>
抄送: hcliu987 ***@***.***>; Author ***@***.***>
主题: Re: [yazhuo-wyze/imaotai] 中奖结果 能否做个通知。。通知中奖就好 (Issue #23)


这个官方就通知啊 短信 app都通知！

―

**Comment by yazhuo-wyze** [comment]
官方会给你发短信的 。

--------------原始邮件--------------
发件人："hcliu987 ***@***.***&gt;;
发送时间：2023年7月11日(星期二) 上午8:00
收件人："yazhuo-wyze/imaotai" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [yazhuo-wyze/imaotai] 中奖结果 能否做个通知。。通知中奖就好 (Issue #23)
-----------------------------------

 

 还有其他手机号，不登录 app 
 
 获取 Outlook for iOS<https://aka.ms/o0ukef&gt; 
 ________________________________ 
 发件人: Liujishou ***@***.***&gt; 
 发送时间: Tuesday, July 11, 2023 12:45:04 AM 
 收件人: yazhuo-wyze/imaotai ***@***.***&gt; 
 抄送: hcliu987 ***@***.***&gt;; Author ***@***.***&gt; 
 主题: Re: [yazhuo-wyze/imaotai] 中奖结果 能否做个通知。。通知中奖就好 (Issue #23) 
 
 
 这个官方就通知啊 短信 app都通知！ 
 
 ―

**Comment by yazhuo-wyze** [comment]
那这个ticket 我先关了哈。
