### ISSUE TITLE
请问这个报错是什么问题啊？

### ISSUE THREAD

**Issue by Yang-jiaxian** [yazhuo-wyze/imaotai#24]
`2023-07-16 09:10:01.787 | WARNING  | process:get_location_count:121 - get_location_count : params : 1689523200000, response code : 404, response body : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key></Key><BucketName></BucketName><Resource>/mt-backend/xhr/front/mall/shop/list/slim/v3/689/广东省/10213/1689523200000</Resource><RequestId>A52WGC5G1K4FAN8Z</RequestId><HostId>PQNV9IS97EKYNP5U</HostId></Error>`

复现图片
![image](https://github.com/yazhuo-wyze/imaotai/assets/69494805/7b3503de-798d-44c3-bee1-1acd45337b91)

**Comment by yazhuo-wyze** [comment]
白天试试。

**Comment by yazhuo-wyze** [comment]
> > 白天试试。
> 
> 上面的日志就是在白天九点多的时候跑的，9点10,40,50 这几个点跑都是相同的错误

可能计算机时区问题。你看看你日志时间。

**Comment by Yang-jiaxian** [comment]
> > > 白天试试。
> > 
> > 
> > 上面的日志就是在白天九点多的时候跑的，9点10,40,50 这几个点跑都是相同的错误
> 
> 可能计算机时区问题。你看看你日志时间。

![image](https://github.com/yazhuo-wyze/imaotai/assets/69494805/a6adf0b7-b897-460e-9131-6965ef333ab2)
当时没有保留日志，我手动改过这个时间假造了一条日志来提问，当时是想着避免你误会我是半夜跑的。（有点多余了）实际情况就是在平时9点10，40，50这几个时间段，跑出来报这个错误。现在我换成是预约位置附近门店，不会出现之前的问题了。我猜应该是我这个地区，在9点10，40，50这几个时间段拿不到本市出货量最大的门店数据，并且可能不是每天都拿不到，是偶尔发生的。
