### ISSUE TITLE
填写地址报错

### ISSUE THREAD

**Issue by 787078720** [yazhuo-wyze/imaotai#29]
<img width="760" alt="屏幕截图 2023-08-01 215059" src="https://github.com/yazhuo-wyze/imaotai/assets/85841713/19dfad40-260a-4b53-907f-c23200fc85b1">

**Comment by 787078720** [comment]
解决了作者的高德key过期了

**Comment by sjzhidong** [comment]
> 

能教教怎么更换高德的key吗？

**Comment by JohnyWu** [comment]
怎么解决？

**Comment by JohnyWu** [comment]
@yazhuo-wyze  怎么解决请教下？

**Comment by JohnyWu** [comment]
> 解决了作者的高德key过期了

怎么解决啊？

**Comment by tangdasan** [comment]
同问，key怎么弄？

**Comment by tangdasan** [comment]
已解决，process.py里的AMAP_KEY 改为自己的就行。
https://console.amap.com/dev/key/app 这里可以申请

**Comment by yazhuo-wyze** [comment]
重新更新一下代码。 使用 了一个网站的 公开接口。https://www.piliang.tech/geocoding-amap。
