### ISSUE TITLE
定时任务是直接写在crontab -e里么？这个要怎么运行起来？

### ISSUE THREAD

**Issue by JohnyWu** [yazhuo-wyze/imaotai#3]
定时任务是直接写在crontab -e里么？这个要怎么运行起来？

**Comment by yazhuo-wyze** [comment]
可以通过crontab -e 写入 ，系统会定期定时自动执行脚本内容。

**Comment by yazhuo-wyze** [comment]
可以手动执行一下，看是不是没日志写入权限。

**Comment by JohnyWu** [comment]
> 可以手动执行一下，看是不是没日志写入权限。

我是管理员权限，正常问题都不大，我测试了一个最简单的任务，也正常写入log了，我再监控下看看

**Comment by JohnyWu** [comment]
遇到了这个错误：xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by JohnyWu** [comment]
但是我同样的命令自己前台执行就没问题

**Comment by JohnyWu** [comment]
我在重新弄xcode

**Comment by yazhuo-wyze** [comment]
> 我在重新弄xcode


> 遇到了这个错误：xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

你用mac 跑 定时任务吗？我用linux 跑的。也不非的用本机跑。可以试试一些免费的CICD 定时任务。

**Comment by JohnyWu** [comment]
都搞定了，问题复杂，偷懒造成的

**Comment by JohnyWu** [comment]
> > 我在重新弄xcode
> 
> > 遇到了这个错误：xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
> 
> 你用mac 跑 定时任务吗？我用linux 跑的。也不非的用本机跑。可以试试一些免费的CICD 定时任务。

代码里当前有邮箱和密码，放本地跑好一些吧？
