### ISSUE TITLE
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message>

### ISSUE THREAD

**Issue by f12f12f12f12** [yazhuo-wyze/imaotai#6]
WARNING: get_location_count : params : 1684857600000, response code : 404, response body : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message>

**Comment by yazhuo-wyze** [comment]
请更新一下代码。
