### ISSUE TITLE
求大佬的抓包方式给个思路吧

### ISSUE THREAD

**Issue by zhongcg** [yazhuo-wyze/imaotai#7]
需要逆向吗，想学习一下

**Comment by yazhuo-wyze** [comment]
> 需要逆向吗，想学习一下

我也不会。

**Comment by zhongcg** [comment]
AES_KEY = 'qbhajinldepmucsonaaaccgypwuvcjaa'
AES_IV = '2018534749963515'
SALT = '2af72f100c356273d46284f6fd1dfc08'
这部分应该要逆向app才能看到吧，还是别的大佬给的呀

**Comment by yazhuo-wyze** [comment]
> AES_KEY = 'qbhajinldepmucsonaaaccgypwuvcjaa' AES_IV = '2018534749963515' SALT = '2af72f100c356273d46284f6fd1dfc08' 这部分应该要逆向app才能看到吧，还是别的大佬给的呀

github上搜的。

**Comment by zhongcg** [comment]
好 我再去研究研究
